In [23]:
import numpy as np

#행렬
#numpy.array(리스트)
x = np.array([3, 1, 2])
print(x)

y = [1, 2, 3]
print(y)

print(type(x)) #원소로 한가지 자료형만 허용
print(type(y)) #원소로 여러 자료형 허용

print(np.array([1,2,'a','b'])) # 숫자를 문자로 출력(한가지 자료형만 허용)

# 내부 배열의 원소 개수가 같아야 함
#np.array([[1,2],[2,3,4],[4,5]]) < 사용불가

print([1,2,3] + [4,5,6])
print(np.array([1,2,3]) + np.array([4,5,6]))
print(np.array([1,2,3]) * np.array([4,5,6]))
print(np.array([1,2,3]) * 3)


[3 1 2]
[1, 2, 3]
<class 'numpy.ndarray'>
<class 'list'>
['1' '2' 'a' 'b']
[1, 2, 3, 4, 5, 6]
[5 7 9]
[ 4 10 18]
[3 6 9]


In [29]:
narray1 = np.array([3, 1, 2])
narray1.ndim

narray2 = np.array([[1,2], [2,3]])
narray2.ndim
narray2.shape

(2, 2)

In [34]:
# dot
n = np.array([1])
n2 = np.array([3])
n.dot(n2)
np.dot(n,n2)

n3 = np.array([1,2,3])
n4 = np.array([4,4,4])
n3.dot(n4)

24

In [90]:
# matmul
n5= np.array([[1,2],[2,3]])
n6= np.array([[1,2],[2,3]])
n5.dot(n6)
np.matmul(n5,n6)

# 0 행렬 생성
np.zeros((5,5))

# 유닛행렬
np.ones((3,3))

# 특정 값 채우기
np.full((3,2), 5)

#단위 행렬(대각선 값 1/ 행 = 열)
np.eye(5)

# 평탄화
# N차원 배열을 1차원 배열로 변환시켜주는 작업
n6.flatten()
n7 = n6.flatten()
list(n7)

# reshape - 원소의 갯수가 같아야함
n8 = np.array([[1,2,3],[4,5,6]])
n8.reshape(3,2)

# arnage 특정 배열을 만듬
np.arange(5)
np.arange(5,10)
np.arange(5,10,2)

#random
np.random.randint(6, size= (2,3))
np.random.rand(3,2) # 0< value <1 요소 값 난수로 생성

# 조건
n = np.array([
    [4,3],
    [2,5],
    [1,9]
])

print(n > 4)

print(n[n > 4] ## 조건에 맞는 인덱스 값으로 배열로 만듬

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[False False]
 [False  True]
 [False  True]]
[5 9]


In [112]:
na = np.zeros((10))
print(na)
na[4] =1
print(na)
print(np.arange(10,31))
print(np.random.randint(100,size =(2,2)))
print(np.random.rand(2,4))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[[30 19]
 [14 47]]
[[0.92127781 0.42905565 0.61506154 0.76223675]
 [0.14085064 0.16205925 0.00329563 0.61519631]]


In [166]:
na2 = np.arange(35,75)
na2 = na2.reshape(10,4)
print(na2)
print()
na3 = na2[::-1,::]
print(na3)
print()
print(na2[1:-1:,2::])

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]

[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]

[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [196]:
print(na2[::,-1::].flatten())
print()
na3 = na2[::,-1::]
print(na3)
print()
print(na3[::-1])
print()

na4 = np.random.randint(1,51, (5,6))
print(na4[na4 % 2 == 0])


[38 42 46 50 54 58 62 66 70 74]

[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]

[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]

[10 24 22 26 26 40 34 34 14 12 26 36  4 20 18 48  4 48]
